megans functions
MeganHebert/shop_data pull request #4
Opened 2024-08-01 20:53 UTC by MeganHebert

2024-08-01 21:07 UTC, Rainmaker0102 requested changes
Good work! Please put these into the main.py file as well as fixing any additional comments

2024-08-01 21:07 UTC, Rainmaker0102 commented on meg_func.py
> +def generate_products():
Please make this into a dynamic provider following this example
```
def exampleProviderFunc():
    example_provider = DynamicProvider(
        provider_name = "example_provider",
        elements = ["my", "elements"],
    )
    return example_provider
```

2024-08-02 18:01 UTC, Rainmaker0102 approved these changes
LGTM!

2024-08-02 19:04 UTC, TonyErazo commented
LGTM

2024-08-02 19:04 UTC, merged